version: '{build}'
shallow_clone: true

platform: x64
configuration:
  - Debug
  - Release

environment:
  MSBUILD_FLAGS: /verbosity:minimal /maxcpucount
  # https://www.appveyor.com/docs/windows-images-software/#qt
  Qt5_INSTALL_DIR: 'C:\Qt\5.13\msvc2017_64'
  
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    CMAKE_GENERATOR: "Visual Studio 16 2019"

matrix:
  fast_finish: true

before_build:
  - cmake --version
  - cmake -S. -Bbuild -G "%CMAKE_GENERATOR%"

build_script:
  - cmake --build build --target ALL_BUILD -- %MSBUILD_FLAGS%

test_script:
  - cmake --build build --target RUN_TESTS -- %MSBUILD_FLAGS%

